# Generated by Django 4.1.1 on 2022-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primernombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
            ],
        ),
    ]
